import type { Metadata } from 'next'
import { AIChat } from '@eic/ui/src/components/organisms/AIChat'
import { Inter } from 'next/font/google'
import { Toaster } from '@eic/ui/src/components/molecules/Toaster'
import { Footer } from '@eic/ui/src/components/organisms/Footer'

import '@eic/ui/src/index.css'

import { AuthProvider } from '@/components/AuthProvider/AuthProvider'
import { Container } from '@eic/ui/src/components/atoms/container'
import { Navbar } from '@eic/ui/src/components/molecules/Navbar'
import { Button } from '@eic/ui/src/components/atoms/button'
import { cn } from '@eic/ui/src/utils'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Editor in cheif | Your personal news editor.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-gray-100')}>
        <AuthProvider>
          <Navbar />
          <Container>
            <div className="py-1" />
            {children}
            <Toaster />

            <div className="fixed bottom-0 right-0 p-2">
              <AIChat />
            </div>
          </Container>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
