import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from '@eic/ui/src/components/molecules/Toaster'

import '@eic/ui/src/index.css'

import { AuthProvider } from '@/components/AuthProvider/AuthProvider'
import { Container } from '@eic/ui/src/components/atoms/container'
import { Navbar } from '@eic/ui/src/components/molecules/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Editor in cheif | Your personal news editor.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Container>
            <Navbar />
            <div className="py-1" />
            {children}
            <Toaster />
          </Container>
        </AuthProvider>
      </body>
    </html>
  )
}
